"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getAdminSubscription,type AdminSubscription} from "../../../../lib/billing";

const money=(n:number,c:string)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:c||"IDR",maximumFractionDigits:0}).format(n/100);
const date=(v:string)=>new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeStyle:"short"}).format(new Date(v));
const labels:Record<string,string>={ACTIVE:"Aktif",TRIAL:"Trial",PAST_DUE:"Perlu perhatian",PENDING:"Menunggu",CANCELLED:"Dibatalkan",EXPIRED:"Kedaluwarsa"};
export default function AdminSubscriptionDetail({params}:{params:Promise<{id:string}>}){
 const[item,setItem]=useState<AdminSubscription|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{void params.then(p=>getAdminSubscription(p.id)).then(setItem).catch(e=>setError(e instanceof Error?e.message:"Subscription tidak ditemukan")).finally(()=>setLoading(false))},[params]);
 if(loading)return <section className="mx-auto max-w-5xl"><div className="rounded-3xl border bg-white p-10 text-sm text-zinc-500">Memuat detail subscription...</div></section>;
 if(error||!item)return <section className="mx-auto max-w-5xl"><Link href="/admin/subscriptions" className="text-sm font-semibold text-amber-700">← Kembali ke subscriptions</Link><div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error||"Subscription tidak ditemukan"}</div></section>;
 return <section className="mx-auto max-w-5xl space-y-6">
  <div><Link href="/admin/subscriptions" className="text-sm font-semibold text-amber-700">← Kembali ke subscriptions</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Billing / Subscription Detail</p><h2 className="mt-2 text-3xl font-bold">{item.workspaceName}</h2><p className="mt-1 text-sm text-zinc-500">Subscription {item.packageName}</p></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-700">{labels[item.status]??item.status}</span></div></div>
  <div className="rounded-3xl bg-zinc-950 p-6 text-white shadow-sm sm:p-8"><div className="grid gap-6 sm:grid-cols-3"><div><p className="text-xs text-zinc-500">Paket</p><p className="mt-1 text-2xl font-bold">{item.packageName}</p><p className="text-xs text-zinc-500">{item.packageCode}</p></div><div><p className="text-xs text-zinc-500">Harga</p><p className="mt-1 text-2xl font-bold">{money(item.amountMinor,item.currency)}</p><p className="text-xs text-zinc-500">{item.billingPeriod==="YEARLY"?"per tahun":"per bulan"}</p></div><div><p className="text-xs text-zinc-500">Provider</p><p className="mt-1 text-2xl font-bold">{item.provider}</p><p className="text-xs text-zinc-500">Mode pembayaran</p></div></div></div>
  <div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Periode Subscription</h3><div className="mt-5 space-y-4"><div><p className="text-xs text-zinc-400">Mulai berlangganan</p><p className="mt-1 text-sm font-semibold">{date(item.startedAt)}</p></div><div><p className="text-xs text-zinc-400">Periode saat ini</p><p className="mt-1 text-sm font-semibold">{date(item.currentPeriodStart)}</p></div><div><p className="text-xs text-zinc-400">Periode berakhir</p><p className="mt-1 text-sm font-semibold">{date(item.currentPeriodEnd)}</p></div>{item.cancelledAt&&<div><p className="text-xs text-zinc-400">Dibatalkan</p><p className="mt-1 text-sm font-semibold text-red-600">{date(item.cancelledAt)}</p></div>}</div></div>
  <div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Identitas Workspace</h3><div className="mt-5 space-y-4"><div><p className="text-xs text-zinc-400">Nama workspace</p><p className="mt-1 text-sm font-semibold">{item.workspaceName}</p></div><div><p className="text-xs text-zinc-400">Workspace ID</p><p className="mt-1 break-all font-mono text-xs text-zinc-600">{item.tenantId}</p></div><div><p className="text-xs text-zinc-400">Subscription dibuat</p><p className="mt-1 text-sm font-semibold">{date(item.createdAt)}</p></div></div></div></div>
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><p className="font-bold">Mode monitoring</p><p className="mt-1 leading-6 text-amber-800">Halaman ini hanya untuk melihat kondisi subscription. Perubahan paket, pembatalan, dan transaksi tetap diproses melalui alur billing yang sesuai agar histori dan data pembayaran tetap konsisten.</p></div>
 </section>;
}