services:
  postgres:
    image: postgres:17
    container_name: personal-developer-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: pda_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: personal_developer_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: