"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getAdminInvoice,type AdminInvoice} from "../../../../lib/billing";

const money=(n:number,c:string)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:c||"IDR",maximumFractionDigits:0}).format(n/100);
const date=(v:string|null)=>v?new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeStyle:"short"}).format(new Date(v)):"—";
const labels:Record<string,string>={SUCCEEDED:"Lunas",PENDING:"Menunggu",FAILED:"Gagal",EXPIRED:"Kedaluwarsa",CANCELLED:"Dibatalkan"};
export default function AdminInvoiceDetail({params}:{params:Promise<{id:string}>}){
 const[item,setItem]=useState<AdminInvoice|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{void params.then(p=>getAdminInvoice(p.id)).then(setItem).catch(e=>setError(e instanceof Error?e.message:"Invoice tidak ditemukan")).finally(()=>setLoading(false))},[params]);
 if(loading)return <section className="mx-auto max-w-5xl"><div className="rounded-3xl border bg-white p-10 text-sm text-zinc-500">Memuat detail invoice...</div></section>;
 if(error||!item)return <section className="mx-auto max-w-5xl"><Link href="/admin/invoices" className="text-sm font-semibold text-amber-700">← Kembali ke invoices</Link><div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error||"Invoice tidak ditemukan"}</div></section>;
 return <section className="mx-auto max-w-5xl space-y-6">
  <div><Link href="/admin/invoices" className="text-sm font-semibold text-amber-700">← Kembali ke invoices</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Billing / Invoice Detail</p><h2 className="mt-2 font-mono text-2xl font-bold">{item.id}</h2><p className="mt-2 text-sm text-zinc-500">{item.workspaceName} · {item.packageName}</p></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-700">{labels[item.status]??item.status}</span></div></div>
  <div className="rounded-3xl bg-zinc-950 p-6 text-white shadow-sm sm:p-8"><div className="grid gap-6 sm:grid-cols-3"><div><p className="text-xs text-zinc-500">Total Invoice</p><p className="mt-1 text-3xl font-bold">{money(item.finalAmountMinor,item.currency)}</p></div><div><p className="text-xs text-zinc-500">Payment Status</p><p className="mt-1 text-2xl font-bold">{item.paymentStatus?labels[item.paymentStatus]??item.paymentStatus:"Belum ada"}</p></div><div><p className="text-xs text-zinc-500">Periode</p><p className="mt-1 text-2xl font-bold">{item.billingPeriod==="YEARLY"?"Tahunan":"Bulanan"}</p></div></div></div>
  <div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Rincian Tagihan</h3><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><span className="text-zinc-500">Subtotal</span><b>{money(item.originalAmountMinor,item.currency)}</b></div><div className="flex justify-between gap-4"><span className="text-zinc-500">Discount</span><b className="text-red-600">-{money(item.discountAmountMinor,item.currency)}</b></div><div className="flex justify-between gap-4"><span className="text-zinc-500">Tax</span><b>{money(item.taxAmountMinor,item.currency)}</b></div><div className="border-t pt-3 flex justify-between gap-4"><span className="font-bold">Total</span><b className="text-lg">{money(item.finalAmountMinor,item.currency)}</b></div></div></div>
  <div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Timeline Invoice</h3><div className="mt-5 space-y-4"><div><p className="text-xs text-zinc-400">Diterbitkan</p><p className="mt-1 text-sm font-semibold">{date(item.issuedAt)}</p></div><div><p className="text-xs text-zinc-400">Jatuh tempo</p><p className="mt-1 text-sm font-semibold">{date(item.dueAt)}</p></div><div><p className="text-xs text-zinc-400">Dibayar</p><p className="mt-1 text-sm font-semibold">{date(item.paidAt)}</p></div><div><p className="text-xs text-zinc-400">Dibuat</p><p className="mt-1 text-sm font-semibold">{date(item.createdAt)}</p></div></div></div></div>
  <div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Relasi Billing</h3><div className="mt-5 grid gap-4 md:grid-cols-3"><div><p className="text-xs text-zinc-400">Workspace</p><p className="mt-1 font-semibold">{item.workspaceName}</p></div><div><p className="text-xs text-zinc-400">Package</p><p className="mt-1 font-semibold">{item.packageName} ({item.packageCode})</p></div><div><p className="text-xs text-zinc-400">Subscription ID</p><p className="mt-1 break-all font-mono text-xs">{item.subscriptionId}</p></div></div></div>
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><p className="font-bold">Mode monitoring</p><p className="mt-1 leading-6 text-amber-800">Invoice tidak dapat diubah dari halaman admin. Status invoice dan payment harus tetap berasal dari alur transaksi agar histori billing konsisten.</p></div>
 </section>;
}