"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { listPackages,seedCatalog,updatePackage,type AdminPackage } from "../../../../lib/billing";

const rupiah=(n:number)=>"Rp "+(n/100).toLocaleString("id-ID");
export default function PackagesPage(){
 const[packages,setPackages]=useState<AdminPackage[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){setLoading(true);try{setPackages(await listPackages())}catch(e){setError(e instanceof Error?e.message:"Gagal memuat package")}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
 async function run(fn:()=>Promise<unknown>,ok:string){setError("");setMessage("");try{await fn();setMessage(ok);await load()}catch(e){setError(e instanceof Error?e.message:"Operasi gagal")}}
 return <section className="mx-auto max-w-7xl space-y-7">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/billing" className="text-sm font-semibold text-zinc-500 hover:text-zinc-900">← Billing</Link><p className="mt-4 text-xs font-bold uppercase tracking-widest text-amber-600">Billing / Plans</p><h2 className="mt-1 text-3xl font-bold">Plans & Prices</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Di sini admin mengatur paket yang ditawarkan kepada pelanggan. Harga dan limit setiap paket dapat dikonfigurasi dari halaman detail.</p></div><button onClick={()=>run(()=>seedCatalog(),"Default billing berhasil disinkronkan")} className="rounded-xl border border-zinc-300 bg-white px-4 py-2.5 text-sm font-semibold hover:bg-zinc-50">Sinkronkan Default</button></div>
  <div className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-sm text-amber-900"><strong>Alur pengaturan:</strong> pilih plan → kelola harga → aktifkan feature → atur limit → aktifkan plan.</div>
  {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  {loading?<div className="rounded-2xl border bg-white p-10 text-center text-sm text-zinc-500">Memuat plans...</div>:<div className="grid gap-5 lg:grid-cols-3">{packages.map((pkg,index)=><article key={pkg.id} className={`relative overflow-hidden rounded-3xl border bg-white shadow-sm ${pkg.isActive?"border-zinc-200":"border-dashed border-zinc-300 opacity-80"}`}><div className="p-6"><div className="flex items-start justify-between"><div><span className="text-xs font-bold text-zinc-400">PLAN {String(index+1).padStart(2,"0")}</span><h3 className="mt-1 text-2xl font-bold">{pkg.name}</h3><p className="font-mono text-xs text-zinc-400">{pkg.code}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${pkg.isActive?"bg-emerald-50 text-emerald-700":"bg-zinc-100 text-zinc-500"}`}>{pkg.isActive?"ACTIVE":"INACTIVE"}</span></div><p className="mt-4 min-h-10 text-sm leading-5 text-zinc-500">{pkg.description||"Belum ada deskripsi."}</p><div className="mt-5 grid grid-cols-2 gap-2">{(pkg.prices??[]).filter(p=>p.isActive).map(p=><div key={p.id} className="rounded-xl bg-zinc-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">{p.billingPeriod==="MONTHLY"?"Per bulan":"Per tahun"}</p><p className="mt-1 text-sm font-bold">{rupiah(p.amountMinor)}</p></div>)}</div><div className="mt-5 border-t pt-4"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">Included capabilities</p><span className="text-xs text-zinc-400">{(pkg.features??[]).filter(x=>x.enabled).length} aktif</span></div><div className="mt-3 space-y-2">{(pkg.features??[]).filter(x=>x.enabled).slice(0,5).map(x=><div key={x.id} className="flex items-center justify-between text-sm"><span className="text-zinc-600">{x.feature?.name??x.featureId}</span><span className="font-semibold">{x.limitValue??"✓"}</span></div>)}{(pkg.features??[]).filter(x=>x.enabled).length>5&&<p className="text-xs text-zinc-400">+ {(pkg.features??[]).filter(x=>x.enabled).length-5} capability lainnya</p>}</div></div><div className="mt-6 grid grid-cols-2 gap-2"><Link href={`/admin/billing/packages/${pkg.id}`} className="rounded-xl bg-zinc-950 px-3 py-2.5 text-center text-xs font-bold text-white">Kelola Plan</Link><button onClick={()=>{const name=prompt("Nama plan",pkg.name);if(name&&name!==pkg.name)void run(()=>updatePackage(pkg.id,{name}),"Nama plan diperbarui")}} className="rounded-xl border px-3 py-2.5 text-xs font-semibold">Ubah Nama</button></div><button onClick={()=>void run(()=>updatePackage(pkg.id,{isActive:!pkg.isActive}),pkg.isActive?"Plan dinonaktifkan":"Plan diaktifkan")} className="mt-2 w-full rounded-xl border px-3 py-2 text-xs font-semibold">{pkg.isActive?"Nonaktifkan Plan":"Aktifkan Plan"}</button></div></article>)}</div>}
 </section>
}