"use client";
import {useEffect,useState} from "react";
import {createFeature,listFeatures,updateFeature,type AdminFeature} from "../../../../lib/billing";
export default function FeaturesPage(){
 const[items,setItems]=useState<AdminFeature[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);try{setItems(await listFeatures())}catch(e){setError(e instanceof Error?e.message:"Gagal memuat feature")}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
 async function add(){const code=prompt("Feature code, contoh API_ACCESS");const name=code&&prompt("Nama feature");if(!code||!name)return;try{await createFeature({code,name,valueType:"BOOLEAN"});await load()}catch(e){setError(e instanceof Error?e.message:"Gagal membuat feature")}}
 const limits=items.filter(x=>x.valueType==="LIMIT").length,booleans=items.filter(x=>x.valueType==="BOOLEAN").length,active=items.filter(x=>x.isActive).length;
 return <section className="mx-auto max-w-7xl space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Billing / Configuration</p><h2 className="mt-1 text-3xl font-bold">Features & Limits</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Feature adalah kemampuan yang bisa dimiliki sebuah plan. Gunakan <strong>LIMIT</strong> untuk fitur yang memiliki batas jumlah, dan <strong>BOOLEAN</strong> untuk fitur ON/OFF.</p></div><button onClick={()=>void add()} className="rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-bold text-white">+ Tambah Feature</button></div>
  <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-zinc-400">TOTAL FEATURES</p><p className="mt-1 text-2xl font-bold">{loading?"—":items.length}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-zinc-400">LIMIT FEATURES</p><p className="mt-1 text-2xl font-bold">{loading?"—":limits}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-zinc-400">ACTIVE</p><p className="mt-1 text-2xl font-bold">{loading?"—":active}</p><p className="text-xs text-zinc-500">{booleans} boolean capability</p></div></div>
  <div className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-sm text-amber-900"><strong>Cara kerja:</strong> buat feature di halaman ini → buka <strong>Plans & Prices</strong> → pilih plan → aktifkan feature → isi limit jika tipenya LIMIT.</div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  {loading?<div className="rounded-2xl border bg-white p-10 text-center text-sm text-zinc-500">Memuat features...</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${item.isActive?"border-zinc-200":"border-dashed border-zinc-300 opacity-70"}`}><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-zinc-950 text-sm font-black text-white">{item.valueType==="LIMIT"?"#":"✓"}</div><button onClick={()=>void updateFeature(item.id,{isActive:!item.isActive}).then(load)} className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${item.isActive?"bg-emerald-50 text-emerald-700":"bg-zinc-100 text-zinc-500"}`}>{item.isActive?"ACTIVE":"INACTIVE"}</button></div><h3 className="mt-4 font-bold">{item.name}</h3><p className="mt-1 font-mono text-[11px] text-zinc-400">{item.code}</p><p className="mt-3 min-h-10 text-sm leading-5 text-zinc-500">{item.description||"Tidak ada deskripsi."}</p><div className="mt-4 flex items-center justify-between border-t pt-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${item.valueType==="LIMIT"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700"}`}>{item.valueType==="LIMIT"?"LIMIT / BERBATAS":"BOOLEAN / ON-OFF"}</span><span className="text-xs font-semibold text-zinc-500">{item.unit||"Tidak ada unit"}</span></div></article>)}</div>}
 </section>
}