"use client";
import Link from "next/link";
import { use, useEffect, useState } from "react";
import { getDiscount,getDiscountPackages,listPackages,setDiscountPackage,updateDiscount,type AdminDiscount, type AdminDiscountPackage, type AdminPackage } from "../../../../../lib/billing";
export default function DiscountDetailPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params); const [item,setItem]=useState<AdminDiscount|null>(null),[packages,setPackages]=useState<AdminPackage[]>([]),[assigned,setAssigned]=useState<AdminDiscountPackage[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const [d,p,a]=await Promise.all([getDiscount(id),listPackages(),getDiscountPackages(id)]);setItem(d);setPackages(p);setAssigned(a)}catch(e){setError(e instanceof Error?e.message:"Gagal memuat detail discount")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[id]);
 async function togglePackage(packageId:string,enabled:boolean){setSaving(true);setError("");try{await setDiscountPackage(id,packageId,enabled);setMessage("Assignment package diperbarui.");await load()}catch(e){setError(e instanceof Error?e.message:"Gagal mengubah assignment")}finally{setSaving(false)}}
 async function toggleActive(){if(!item)return;setSaving(true);setError("");try{await updateDiscount(id,{isActive:!item.isActive});setMessage("Status discount diperbarui.");await load()}catch(e){setError(e instanceof Error?e.message:"Gagal memperbarui discount")}finally{setSaving(false)}}
 if(loading)return <section><p>Memuat...</p></section>;
 if(!item)return <section><p>Discount tidak ditemukan.</p></section>;
 const has=(pid:string)=>assigned.some(x=>x.packageId===pid);
 return <section className="mx-auto max-w-5xl space-y-6">
  <div><Link href="/admin/billing/discounts" className="text-sm font-semibold text-zinc-500">← Discounts</Link><p className="mt-4 text-sm font-semibold text-amber-600">Discount Detail</p><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="mt-1 text-3xl font-bold">{item.code}</h2><p className="mt-1 text-zinc-500">{item.name}</p></div><button onClick={()=>void toggleActive()} disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold">{item.isActive?"Deactivate":"Activate"}</button></div></div>
  {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Configuration</h3><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>Type</dt><dd className="font-semibold">{item.type}</dd></div><div className="flex justify-between"><dt>Value</dt><dd className="font-semibold">{item.type==="PERCENTAGE"?String(item.percentage)+"%":"Rp "+((item.valueMinor??0)/100).toLocaleString("id-ID")}</dd></div><div className="flex justify-between"><dt>Duration</dt><dd className="font-semibold">{item.duration}{item.durationCycles?" · "+item.durationCycles+" cycles":""}</dd></div><div className="flex justify-between"><dt>Minimum</dt><dd className="font-semibold">{item.minimumAmountMinor===null?"-":"Rp "+(item.minimumAmountMinor/100).toLocaleString("id-ID")}</dd></div><div className="flex justify-between"><dt>Usage</dt><dd className="font-semibold">{item.usageCount}{item.usageLimit===null?" / ∞":" / "+item.usageLimit}</dd></div></dl></div>
  <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Validity</h3><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt>Starts</dt><dd className="font-semibold">{item.startsAt?new Date(item.startsAt).toLocaleString("id-ID"):"-"}</dd></div><div className="flex justify-between gap-4"><dt>Expires</dt><dd className="font-semibold">{item.expiresAt?new Date(item.expiresAt).toLocaleString("id-ID"):"-"}</dd></div><div className="flex justify-between"><dt>Status</dt><dd className="font-semibold">{item.isActive?"ACTIVE":"INACTIVE"}</dd></div></dl></div></div>
  <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Package Assignment</h3><p className="mt-1 text-sm text-zinc-500">Discount hanya dapat dipilih untuk package yang diaktifkan di sini.</p><div className="mt-4 divide-y">{packages.map(p=><div key={p.id} className="flex items-center justify-between py-4"><div><p className="font-semibold">{p.name}</p><p className="text-xs text-zinc-400">{p.code}</p></div><button onClick={()=>void togglePackage(p.id,!has(p.id))} disabled={saving} className={has(p.id)?"rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700":"rounded-full bg-zinc-100 px-3 py-1.5 text-xs font-bold text-zinc-600"}>{has(p.id)?"ASSIGNED":"ASSIGN"}</button></div>)}</div></div>
 </section>
}